---
- name: Converge
  hosts: localhost
  gather_facts: false
  vars: 
  - k8s_dashboard_kubeconfig: ""
  tasks:
    - name: "Include garliclabs.ansible_role_ensure_k8s_dashboard_state"
      ansible.builtin.include_role:
        name: "ansible_role_ensure_k8s_dashboard_state"